src/components/EpochDetails/EpochPrediction.tsx
src/components/EpochDetails/EpochPrice.tsx
src/components/EpochDisplay.tsx
src/contexts/PredictoorsContext.tsx
src/styles/Epoch.module.css

Fix subscribed predictions only visible on new epoch fetch

---

src/components/EpochDisplay.tsx
src/components/Price.tsx
src/contexts/MarketPriceContextHelpers.ts

Fixes #227 
Price direction issue and refactoring on the EpochDisplay component

PriceDeltaIssue

---

src/components/Stake.tsx

App crushes because totakStake is undefined

fix totalStake is undefined

---

src/components/AssetRow.tsx
src/components/Footer.tsx
src/utils/config.ts
src/utils/getInitialData.ts
src/utils/localStorage/getSignedMessageFromLS.ts
src/utils/networkProvider.ts
src/utils/utils.ts

Add support for Sapphire mainnet

---

src/components/AssetRow.tsx
src/components/Stake.tsx

Fixes:
- display stats with 1 decimal
- in delta calculation last 24h stakes and current 24h stakes are switched

Fix stake stats

---

src/components/Stake.tsx

Remove console log

---

src/components/EpochDetails/EpochStakedTokens.tsx
src/components/MenuList.tsx

Link to other network deployments and updated staked amount display 

---

src/components/Banner.tsx
src/contexts/PredictoorsContext.tsx
src/contexts/PredictoorsContext.types.ts
src/contexts/UserContext.tsx
src/styles/Banner.module.css
src/utils/authorize.ts

User signature UX improvements

---

src/components/MenuList.tsx

Point about link to predictoor docs

---

src/styles/Epoch.module.css
src/styles/globals.css

Make staked amounts easier to read

---

src/components/Subscription.tsx
src/elements/Button.tsx
src/styles/Button.module.css

Add loading wheel to subscription button

---

src/utils/config.ts

Filter out Binanceus prediction contracts

---

src/components/AssetTable.tsx
src/components/AssetsContainer.tsx
src/components/NotConnectedWarning.tsx
src/pages/_app.tsx

Optimize app initialization

---

src/components/AssetRow.tsx
src/contexts/PredictoorsContext.tsx
src/utils/subgraphs/getAssetAccuracy.ts
src/utils/subgraphs/queries/getPredictSlots.ts

Fixes #269 
Changes proposed in this PR:

issue269: Prevent Multiple Refresh and Fetches

---

package-lock.json
package.json

updated posthog to latest version

---

src/contexts/MarketPriceContext.tsx
src/utils/endpoints/thirdPartyEndpoints.ts

Fixes #275
Changes proposed in this PR:
- Update Binance endpoint to remove US restriction
- 
-

Update Binance endpoint to remove US restriction

---

src/components/ArrowDown.tsx
src/components/ArrowUp.tsx
src/components/AssetRow.tsx
src/components/AssetTable.tsx
src/components/AssetsContainer.tsx
src/components/Header.tsx
src/components/MenuList.tsx
src/components/TimeFrameSwitch.tsx
src/elements/BurgerMenuButton.tsx
src/styles/AssetsTable.module.css
src/styles/Banner.module.css
src/styles/BurgerMenuButton.module.css
src/styles/Header.module.css
src/styles/MenuList.module.css
src/styles/Table.module.css
src/styles/Wallet.module.css

Fixes #151 
Changes proposed in this PR:

issue151 : Mobile Version

---

src/components/AssetTable.tsx
src/metadata/tootltips.ts

Fixes #291 
Changes proposed in this PR:
- the label of the accuracy column is fixed
- the tooltip is fixed

issue291 label fix

---

src/utils/contracts/Predictoor.ts

Fix subscription purchase

---

src/contexts/MarketPriceContextHelpers.ts

Fix app crushes on no price data

---

src/components/MenuList.tsx

Fix #302: Point to new location of docs

---

src/contexts/MarketPriceContext.tsx

Harden price api reliability

---

src/components/MenuList.tsx

Header menu links updates
